const actionTypes = {
  HANDLE_SCORE: "HANDLE_SCORE",
  HANDLE_NAME: "HANDLE_NAME",
  HANDLE_CURRENT_QUESTION: "HANDLE_CURRENT_QUESTION",
  HANDLE_ANSWER_QUESTION: "HANDLE_ANSWER_QUESTION",
  HANDLE_NEXT_QUESTION: "HANDLE_NEXT_QUESTION",
};

export default actionTypes;
