const actionType = {
  HANDLE_ANSWER_QUESTION: "HANDLE_ANSWER_QUESTION",
  HANDLE_NAME: "HANDLE_NAME",
  HANDLE_SCORE: "HANDLE_SCORE",
  HANDLE_QUIZ_STATE: "HANDLE_QUIZ_STATE",
};

export default actionType;
